### ISSUE TITLE
Database error -> error creating tables: unable to open database file: out of memory (14)

### ISSUE THREAD

**Issue by iHarshad** [mr-karan/gullak#6]
I am running gullak using rootless podman. The container is built successfully as I get an `exit code: 0` message. I have made minor changes to the `Dockerfile` and `docker-compose.yml`. 

<details>
  <summary>Error log</summary>
  
  Command: `$ podman logs -ft --details backend`
  
  ```bash
  2024-10-16T16:45:03.324330000+05:30 time=2024-10-16T11:15:03.324Z level=INFO msg="Successfully initialized OpenAI client" model=gpt-4o
  2024-10-16T16:45:03.325637000+05:30 time=2024-10-16T11:15:03.324Z level=ERROR msg="Error initializing database" error="error creating tables: unable to open database file: out of memory (14)"
  ```  
</details>

<details>
  <summary>Dockerfile edits</summary>
  
  ```diff
  diff --git a/Dockerfile b/Dockerfile
index 04f33bb..a6887f1 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,13 +1,13 @@
-FROM golang:1.22.4 AS builder
+FROM docker.io/library/golang:1.22.4 AS builder
 WORKDIR /app/build

 # Copy the binary
 COPY --from=builder /app/build/bin/gullak.bin ./gullak.bin
-COPY config.sample.toml config.toml
+COPY config.toml config.toml

  ```  
</details>

<details>
  <summary>docker-compose.yml edits</summary>
    I need the database to persist, hence adding volumes.
    
  ```diff
  diff --git a/docker-compose.yml b/docker-compose.yml
index 1120208..23a5c75 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -2,8 +2,11 @@
 version: "3.8"
 services:
   backend:
+    container_name: backend
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - 3333:3333
+    volumes:
+      - $DOCKER_DATA_VOL/gullak:/vol

  ```  
</details>

<details>
  <summary>config.toml</summary>
  
  ```toml
  [app]
debug = true
currency = "INR"
db_path = "./vol/expenses.db"

[http]
enabled=true
address=":3333"
timeout="30s"

[openai]
base_url = "https://api.openai.com"
token = "xxxxx"
model = "gpt-4o"
timeout = "10s"
  ```  
</details>
